### PR TITLE
fix: add old partitions constructor for backwards compatibility

### PR DESCRIPTION
**Pull request by 0marperez**
## Issue \#
Possible fix for : https://github.com/awslabs/aws-sdk-kotlin/issues/1411 

## Description of changes
This is re-adding a constructor that was removed from Kotlin to fix backwards incompatibility between versions < 1.2.8 to 1.3.39. 

Relevant PR: https://github.com/awslabs/aws-sdk-kotlin/pull/1335

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ianbotsf — APPROVED** [review]

**Comment by drayan85** [comment]
Could you provide an estimated timeline for when this fix might be available in the next version? 

FYI, we are experiencing significant user crashes in production (https://github.com/awslabs/aws-sdk-kotlin/issues/1425). With this fix, we'd like to try the latest version to determine if the issue is resolved.

**Comment by drayan85** [comment]
This has been 2 weeks already and we are facing some crashes due to the old version in our production app. 😞

**Comment by drayan85** [comment]
Any updates ?

**Comment by ianbotsf** [comment]
I'm working on updating this PR today. Hopefully we'll get it approved and released in the next day or two.

**Review by lauzadis — APPROVED** [review]

**Comment by ianbotsf** [comment]
@drayan85 this change has been merged and should be present in today's SDK release **v1.3.60**.

**Comment by drayan85** [comment]
Thanks

**Pull request merged**
